# Generated by Django 4.2.9 on 2024-04-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(choices=[('0', '0-18'), ('1', '18-24'), ('2', '24-65'), ('3', '65+')], max_length=1)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('Q1', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('Q2', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('Q3', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('Q4', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('Q5', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('Q6', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
            ],
        ),
    ]
